flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
  - LibZip-1.0.1
  - binary-state-0.1.1
  - control-monad-exception-0.11.2
  - failure-0.2.0.3
  - text-1.2.2.1
  - ghc-mod-5.6.0.0
  - cabal-helper-0.7.2.0
  - cabal-install-1.24.0.0
resolver: lts-7.1
